package com.oss.osscourse.mapper;

import com.oss.osscourse.dto.trace.AchievementLedgerRow;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

@Mapper
public interface AchievementTraceMapper {

    @Select({
            "<script>",
            "SELECT",
            "  m.major_id AS majorId,",
            "  m.major_name AS majorName,",
            "  gr.grade_year AS gradeYear,",
            "  term.term_id AS termId,",
            "  term.term_code AS termCode,",
            "  gr.gr_id AS grId,",
            "  gr.gr_code AS grCode,",
            "  gr.gr_description AS grDescription,",
            "  ip.ip_id AS ipId,",
            "  ip.ip_code AS ipCode,",
            "  ip.ip_description AS ipDescription,",
            "  mia.final_achievement AS finalAchievement,",
            "  c.course_id AS courseId,",
            "  c.course_code AS courseCode,",
            "  c.course_name AS courseName,",
            "  tc.class_id AS classId,",
            "  tc.class_code AS classCode,",
            "  tc.class_name AS className,",
            "  tc.calc_status AS calcStatus,",
            "  cia.achievement AS courseIndicatorAchievement,",
            "  cis.total_weight AS macroWeight,",
            "  co.co_id AS coId,",
            "  co.objective_code AS objectiveCode,",
            "  co.co_description AS coDescription,",
            "  coa.average_achievement AS objectiveAchievement,",
            "  oic.internal_weight AS internalWeight,",
            "  ap.ap_id AS apId,",
            "  ap.ap_name AS apName,",
            "  ap.full_score AS fullScore,",
            "  s.student_id AS studentId,",
            "  s.student_no AS studentNo,",
            "  s.student_name AS studentName,",
            "  sas.actual_score AS actualScore",
            "FROM graduation_requirement gr",
            "JOIN major m ON m.major_id = gr.major_id",
            "JOIN indicator_point ip ON ip.gr_id = gr.gr_id",
            "LEFT JOIN major_indicator_achievement mia",
            "  ON mia.major_id = gr.major_id",
            " AND mia.grade_year = gr.grade_year",
            " AND mia.ip_id = ip.ip_id",
            " <if test='termId != null'>AND mia.term_id = #{termId}</if>",
            "JOIN course_indicator_support cis ON cis.ip_id = ip.ip_id",
            "JOIN course_major cm",
            "  ON cm.course_id = cis.course_id",
            " AND cm.major_id = gr.major_id",
            " AND cm.grade_year = gr.grade_year",
            "JOIN course c ON c.course_id = cis.course_id",
            "LEFT JOIN teaching_class tc",
            "  ON tc.course_id = c.course_id",
            " AND tc.grade_year = gr.grade_year",
            " <if test='termId != null'>AND tc.term_id = #{termId}</if>",
            "LEFT JOIN academic_term term ON term.term_id = COALESCE(mia.term_id, tc.term_id)",
            "LEFT JOIN course_indicator_achievement cia",
            "  ON cia.class_id = tc.class_id",
            " AND cia.ip_id = ip.ip_id",
            "LEFT JOIN objective_indicator_contribution oic",
            "  ON oic.ip_id = ip.ip_id",
            " AND EXISTS (",
            "   SELECT 1 FROM course_objective co_check",
            "   WHERE co_check.co_id = oic.co_id",
            "     AND co_check.course_id = c.course_id",
            " )",
            "LEFT JOIN course_objective co ON co.co_id = oic.co_id",
            "LEFT JOIN course_objective_achievement coa",
            "  ON coa.class_id = tc.class_id",
            " AND coa.co_id = co.co_id",
            "LEFT JOIN assessment_point ap ON ap.co_id = co.co_id",
            "LEFT JOIN student_assessment_score sas",
            "  ON sas.class_id = tc.class_id",
            " AND sas.ap_id = ap.ap_id",
            "LEFT JOIN student s",
            "  ON s.student_id = sas.student_id",
            " AND s.major_id = gr.major_id",
            " AND s.enrollment_year = gr.grade_year",
            "WHERE gr.major_id = #{majorId}",
            "  AND gr.grade_year = #{gradeYear}",
            "  AND gr.status = 1",
            "  AND ip.status = 1",
            " <if test='ipId != null'>AND ip.ip_id = #{ipId}</if>",
            "ORDER BY gr.gr_code ASC, ip.ip_code ASC, c.course_code ASC,",
            "         tc.class_code ASC, co.objective_code ASC, ap.ap_id ASC, s.student_no ASC",
            "</script>"
    })
    List<AchievementLedgerRow> selectLedgerRows(@Param("majorId") Long majorId,
                                                @Param("gradeYear") Integer gradeYear,
                                                @Param("termId") Long termId,
                                                @Param("ipId") Long ipId);
}
