events {}

http {
  upstream backend_server {
    server host.docker.internal:8080;
  }

  upstream frontend_server {
    server frontend:80;
  }

  server {
    listen 80;

    location /api/ {
      proxy_pass http://backend_server/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /health {
      proxy_pass http://backend_server/health;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
      proxy_pass http://frontend_server/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
